{% set name = "qdax" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qdax-{{ version }}.tar.gz
  sha256: 841384811c39561e941e109c64480590d84df7b045dbe4690594bd9e153429ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - absl-py >=1.0.0
    - jax >=0.3.10
    - jaxlib >=0.3.10
    - flax >=0.4.1
    - brax >=0.0.12
    - gym >=0.24.0
    - scikit-learn >=1.0.2
    - scipy >=1.8.0

test:
  imports:
    - qdax
  commands:
    - python -c "from qdax.core.map_elites import MAPElites; from qdax.utils.metrics import default_qd_metrics"

about:
  home: https://github.com/adaptive-intelligent-robotics/QDax
  summary: A Python Library for Quality-Diversity and NeuroEvolution
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
