context:
  name: qdax
  version: 0.4.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/qdax-${{ version }}.tar.gz
  sha256: 28bda31d7c65cdfe0c177b75176341922906efc8ec4f3a30a374ef996661c9cd

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - numpy
    - absl-py >=1.0.0
    - jax >=0.3.10
    - jaxlib >=0.3.10
    - flax >=0.4.1
    - brax >=0.0.12
    - gym >=0.24.0
    - scikit-learn >=1.0.2
    - scipy >=1.8.0

tests:
  - python:
      imports:
        - qdax
  - script:
      - "python -c \"from qdax.core.map_elites import MAPElites; from qdax.utils.metrics import default_qd_metrics\""

about:
  summary: A Python Library for Quality-Diversity and NeuroEvolution
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/adaptive-intelligent-robotics/QDax

extra:
  recipe-maintainers:
    - Tobias-Fischer
